version: '3.8'

services:
  ascobra-sysfinanciero:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"   # Exponer el puerto 80
      - "443:443" # Exponer el puerto 443
    environment:
      ASPNETCORE_ENVIRONMENT: Development # Ajusta seg√∫n tus necesidades
    volumes:
      - .:/app # Montar el directorio actual en /app dentro del contenedor